[2025-08-10T02:20:38.395+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-10T02:20:38.487+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: playstore_review_pipeline.scrape_new_reviews manual__2025-08-10T02:15:34.405212+00:00 [queued]>
[2025-08-10T02:20:38.511+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: playstore_review_pipeline.scrape_new_reviews manual__2025-08-10T02:15:34.405212+00:00 [queued]>
[2025-08-10T02:20:38.515+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-10T02:20:38.557+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): scrape_new_reviews> on 2025-08-10 02:15:34.405212+00:00
[2025-08-10T02:20:38.580+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'playstore_review_pipeline', 'scrape_new_reviews', 'manual__2025-08-10T02:15:34.405212+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/playstore_pipeline_dag.py', '--cfg-path', '/tmp/tmp5gcypcdx']
[2025-08-10T02:20:38.589+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask scrape_new_reviews
[2025-08-10T02:20:38.589+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=274) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-10T02:20:38.591+0000] {standard_task_runner.py:63} INFO - Started process 275 to run task
[2025-08-10T02:20:38.708+0000] {task_command.py:426} INFO - Running <TaskInstance: playstore_review_pipeline.scrape_new_reviews manual__2025-08-10T02:15:34.405212+00:00 [running]> on host 923e0e487251
[2025-08-10T02:20:39.019+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='playstore_review_pipeline' AIRFLOW_CTX_TASK_ID='scrape_new_reviews' AIRFLOW_CTX_EXECUTION_DATE='2025-08-10T02:15:34.405212+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-10T02:15:34.405212+00:00'
[2025-08-10T02:20:39.025+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-10T02:20:39.139+0000] {logging_mixin.py:188} INFO - Error in scraper: No module named 'google_play_scraper'
[2025-08-10T02:20:39.141+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-10T02:20:39.144+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/playstore_pipeline_dag.py", line 21, in run_scraper
    import scraper # Imports scraper/scraper.py
    ^^^^^^^^^^^^^^
  File "/opt/airflow/scraper_code/scraper.py", line 4, in <module>
    from google_play_scraper import reviews, Sort
ModuleNotFoundError: No module named 'google_play_scraper'
[2025-08-10T02:20:39.222+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=playstore_review_pipeline, task_id=scrape_new_reviews, run_id=manual__2025-08-10T02:15:34.405212+00:00, execution_date=20250810T021534, start_date=20250810T022038, end_date=20250810T022039
[2025-08-10T02:20:39.274+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task scrape_new_reviews (No module named 'google_play_scraper'; 275)
[2025-08-10T02:20:39.314+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-10T02:20:39.372+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-10T02:20:39.376+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
