[2025-08-11T02:00:02.699+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-11T02:00:02.860+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: playstore_review_pipeline.scrape_new_reviews manual__2025-08-11T02:00:00.152030+00:00 [queued]>
[2025-08-11T02:00:02.899+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: playstore_review_pipeline.scrape_new_reviews manual__2025-08-11T02:00:00.152030+00:00 [queued]>
[2025-08-11T02:00:02.903+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-11T02:00:02.946+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): scrape_new_reviews> on 2025-08-11 02:00:00.152030+00:00
[2025-08-11T02:00:02.979+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'playstore_review_pipeline', 'scrape_new_reviews', 'manual__2025-08-11T02:00:00.152030+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/playstore_pipeline_dag.py', '--cfg-path', '/tmp/tmp053t6ea6']
[2025-08-11T02:00:02.991+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=387) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-11T02:00:02.994+0000] {standard_task_runner.py:63} INFO - Started process 388 to run task
[2025-08-11T02:00:02.993+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask scrape_new_reviews
[2025-08-11T02:00:03.294+0000] {task_command.py:426} INFO - Running <TaskInstance: playstore_review_pipeline.scrape_new_reviews manual__2025-08-11T02:00:00.152030+00:00 [running]> on host 923e0e487251
[2025-08-11T02:00:03.745+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='playstore_review_pipeline' AIRFLOW_CTX_TASK_ID='scrape_new_reviews' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T02:00:00.152030+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-11T02:00:00.152030+00:00'
[2025-08-11T02:00:03.751+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-11T02:00:04.052+0000] {logging_mixin.py:188} INFO - Error in scraper: No module named 'google_play_scraper'
[2025-08-11T02:00:04.057+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-11T02:00:04.059+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/playstore_pipeline_dag.py", line 21, in run_scraper
    import scraper # Imports scraper/scraper.py
    ^^^^^^^^^^^^^^
  File "/opt/airflow/scraper_code/scraper.py", line 4, in <module>
    from google_play_scraper import reviews, Sort
ModuleNotFoundError: No module named 'google_play_scraper'
[2025-08-11T02:00:04.108+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=playstore_review_pipeline, task_id=scrape_new_reviews, run_id=manual__2025-08-11T02:00:00.152030+00:00, execution_date=20250811T020000, start_date=20250811T020002, end_date=20250811T020004
[2025-08-11T02:00:04.139+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task scrape_new_reviews (No module named 'google_play_scraper'; 388)
[2025-08-11T02:00:04.185+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-11T02:00:04.237+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-11T02:00:04.243+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
